version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__STORAGE__PATH=/qdrant/storage
      - QDRANT__LOG_LEVEL=info

volumes:
  qdrant_storage:
